localuri_address:
    resource: "@LocaluriAddressBundle/Resources/config/routing.yml"
    prefix:   /

#todo: change this
homepage:
    pattern:  /
    defaults: { _controller: LocaluriUserBundle:User:myAccount }
    requirements:
        _method:  GET


#Bundles' routes
localuri_user:
    resource: "@LocaluriUserBundle/Resources/config/routing.yml"

localuri_log:
    resource: "@LocaluriLogBundle/Resources/config/routing.yml"


#FosUserBundle Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
